---
### Problem 1 — Imports and Data Loading

নিচের সব library import করো:
- `numpy`, `pandas`
- `sklearn` থেকে: `train_test_split`, `SimpleImputer`, `OrdinalEncoder`, `OneHotEncoder`, `LabelEncoder`, `StandardScaler`, `MinMaxScaler`, `Pipeline`, `ColumnTransformer`, `LogisticRegression`

`titanic_data_updated.csv` লোড করো `df` নামে এবং প্রথম 5টি row দেখাও।

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv("titanic_data_updated.csv")
df.head(10)

   PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
0            1       no   third  ...   7.2500   NaN         S
1            2      yes   first  ...  71.2833   C85         C
2            3      yes   third  ...   7.9250   NaN         S
3            4      yes   first  ...  53.1000  C123         S
4            5       no   third  ...   8.0500   NaN         S
5            6       no   third  ...   8.4583   NaN         Q
6            7       no   first  ...  51.8625   E46         S
7            8       no   third  ...  21.0750   NaN         S
8            9      yes   third  ...  11.1333   NaN         S
9           10      yes  second  ...  30.0708   NaN         C

[10 rows x 12 columns]

---
### Problem 2 — Feature Engineering

দুটি নতুন column তৈরি করো:

1. `Family_Size` — formula: `SibSp + Parch + 1`
2. `Deck` — `Cabin` column-এর NaN গুলো `"Missing"` দিয়ে fill করো, তারপর প্রথম character নিয়ে `Deck` column তৈরি করো

শেষে `df.sample(5)` দিয়ে result দেখাও।

In [5]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

     PassengerId Survived  Pclass                               Name  ...    Cabin  Embarked  Family_Size  Deck
288          289      yes  second               Hosono, Mr. Masabumi  ...  Missing         S            1     M
280          281       no   third                   Duane, Mr. Frank  ...  Missing         Q            1     M
707          708      yes   first  Calderhead, Mr. Edward Pennington  ...      E24         S            1     E
657          658       no   third      Bourke, Mrs. John (Catherine)  ...  Missing         Q            3     M
762          763      yes   third              Barah, Mr. Hanna Assi  ...  Missing         C            1     M

[5 rows x 14 columns]